/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package cadastroView;

import dao.ProdutoGradeDAO;
import java.util.ArrayList;
import java.util.List;
import javax.swing.JOptionPane;
import javax.swing.table.DefaultTableModel;
import model.Produto;
import model.ProdutoGrade;
import model.ProdutoGradeItens;

/**
 *
 * @author daniel
 */
public class ProdutoGradeView extends javax.swing.JDialog {

    /**
     * Creates new form ProdutoGradeTesteView
     */
    
    private ProdutoGradeItenView produtoGradeItenView;
    private ProdutoGrade produtoGrade;
    private Produto produto;
    String tipoBotao;
    List<ProdutoGradeItens> listaItensGrade;
    public ProdutoGradeView(java.awt.Frame parent, boolean modal, Produto produto, 
    ProdutoGrade produtoGrade, String tipoBotao) {
        super(parent, modal);
        initComponents();        
        this.produtoGrade = new ProdutoGrade();
        this.produto = new Produto();
        jlProduto.setText(produto.getDescricao());
        if (tipoBotao.equals("adicionar")) {
            jbtExcluir.setEnabled(false);
            jbtCancelar.setEnabled(true);
            jbtAtributosGrade.setEnabled(false);
        }else {
            if (tipoBotao.equals("alterar")){
                DefaultTableModel amodel = (DefaultTableModel) jTable1.getModel();
                amodel.setNumRows(0);
                
                this.produtoGrade = produtoGrade;
                jtfGrade.setText(this.produtoGrade.getGrade());
                
                for (ProdutoGradeItens pgi : this.produtoGrade.getListaGradeItens()){     
                    
                    amodel.addRow(new Object[]{pgi.getAtributo(), 
                    pgi.getEstoqueMinimo(), pgi.getEstoque(), pgi.getId()});
                }              
                jbtAtributosGrade.setEnabled(true);
            }
        }
        jbtSalvar.setEnabled(true);
        this.produto = produto;
        this.tipoBotao = tipoBotao;
        
        
    }

    private void limpar(){
        DefaultTableModel amodel = (DefaultTableModel) jTable1.getModel();
        jtfGrade.setText("");
        amodel.setNumRows(0);
    }
    
    
    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel1 = new javax.swing.JPanel();
        jLabel1 = new javax.swing.JLabel();
        jtfGrade = new javax.swing.JTextField();
        jlProduto = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        jPanel4 = new javax.swing.JPanel();
        jbtExcluir = new javax.swing.JButton();
        jbtCancelar = new javax.swing.JButton();
        jbtSair = new javax.swing.JButton();
        jbtSalvar = new javax.swing.JButton();
        jbtAtributosGrade = new javax.swing.JButton();
        jScrollPane1 = new javax.swing.JScrollPane();
        jTable1 = new javax.swing.JTable();

        setDefaultCloseOperation(javax.swing.WindowConstants.DISPOSE_ON_CLOSE);

        jPanel1.setBorder(javax.swing.BorderFactory.createTitledBorder("Grade de  produto"));

        jLabel1.setText("Produto");

        jtfGrade.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyPressed(java.awt.event.KeyEvent evt) {
                jtfGradeKeyPressed(evt);
            }
        });

        jlProduto.setFont(new java.awt.Font("Ubuntu", 1, 18)); // NOI18N
        jlProduto.setText("DescricaoProduto");

        jLabel3.setText("Grade");

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel1Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jLabel1)
                    .addComponent(jlProduto))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jtfGrade, javax.swing.GroupLayout.PREFERRED_SIZE, 207, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel3))
                .addContainerGap())
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel1)
                    .addComponent(jLabel3))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jtfGrade, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jlProduto))
                .addContainerGap())
        );

        jPanel4.setBorder(javax.swing.BorderFactory.createEtchedBorder());

        jbtExcluir.setIcon(new javax.swing.ImageIcon(getClass().getResource("/imagens/delete.png"))); // NOI18N
        jbtExcluir.setText("Excluir");
        jbtExcluir.setEnabled(false);
        jbtExcluir.setFocusCycleRoot(true);
        jbtExcluir.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jbtExcluirActionPerformed(evt);
            }
        });
        jbtExcluir.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyPressed(java.awt.event.KeyEvent evt) {
                jbtExcluirKeyPressed(evt);
            }
        });

        jbtCancelar.setIcon(new javax.swing.ImageIcon(getClass().getResource("/imagens/cancel.png"))); // NOI18N
        jbtCancelar.setText("Cancelar");
        jbtCancelar.setEnabled(false);
        jbtCancelar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jbtCancelarActionPerformed(evt);
            }
        });
        jbtCancelar.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyPressed(java.awt.event.KeyEvent evt) {
                jbtCancelarKeyPressed(evt);
            }
        });

        jbtSair.setIcon(new javax.swing.ImageIcon(getClass().getResource("/imagens/exit_1.png"))); // NOI18N
        jbtSair.setText("Sair");
        jbtSair.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jbtSairActionPerformed(evt);
            }
        });
        jbtSair.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyPressed(java.awt.event.KeyEvent evt) {
                jbtSairKeyPressed(evt);
            }
        });

        jbtSalvar.setIcon(new javax.swing.ImageIcon(getClass().getResource("/imagens/save.png"))); // NOI18N
        jbtSalvar.setText("Salvar");
        jbtSalvar.setEnabled(false);
        jbtSalvar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jbtSalvarActionPerformed(evt);
            }
        });
        jbtSalvar.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyPressed(java.awt.event.KeyEvent evt) {
                jbtSalvarKeyPressed(evt);
            }
        });

        javax.swing.GroupLayout jPanel4Layout = new javax.swing.GroupLayout(jPanel4);
        jPanel4.setLayout(jPanel4Layout);
        jPanel4Layout.setHorizontalGroup(
            jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel4Layout.createSequentialGroup()
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(jbtCancelar, javax.swing.GroupLayout.PREFERRED_SIZE, 119, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jbtExcluir, javax.swing.GroupLayout.PREFERRED_SIZE, 107, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jbtSalvar, javax.swing.GroupLayout.PREFERRED_SIZE, 115, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jbtSair, javax.swing.GroupLayout.PREFERRED_SIZE, 95, javax.swing.GroupLayout.PREFERRED_SIZE))
        );
        jPanel4Layout.setVerticalGroup(
            jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                .addComponent(jbtCancelar, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(jbtExcluir, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(jbtSair)
                .addComponent(jbtSalvar, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        jbtAtributosGrade.setIcon(new javax.swing.ImageIcon(getClass().getResource("/imagens/Add.png"))); // NOI18N
        jbtAtributosGrade.setText("Atributos da grade");
        jbtAtributosGrade.setNextFocusableComponent(jbtSalvar);
        jbtAtributosGrade.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jbtAtributosGradeActionPerformed(evt);
            }
        });

        jTable1.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {

            },
            new String [] {
                "ATRIBUTO (cor, tamanho, peso ...)", "ESTOQUE MÍNIMO", "ESTOQUE", "Id"
            }
        ) {
            Class[] types = new Class [] {
                java.lang.String.class, java.lang.Float.class, java.lang.Float.class, java.lang.Long.class
            };
            boolean[] canEdit = new boolean [] {
                true, true, true, false
            };

            public Class getColumnClass(int columnIndex) {
                return types [columnIndex];
            }

            public boolean isCellEditable(int rowIndex, int columnIndex) {
                return canEdit [columnIndex];
            }
        });
        jTable1.setAutoResizeMode(javax.swing.JTable.AUTO_RESIZE_OFF);
        jTable1.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jTable1MouseClicked(evt);
            }
        });
        jScrollPane1.setViewportView(jTable1);
        if (jTable1.getColumnModel().getColumnCount() > 0) {
            jTable1.getColumnModel().getColumn(0).setPreferredWidth(240);
            jTable1.getColumnModel().getColumn(1).setPreferredWidth(150);
            jTable1.getColumnModel().getColumn(2).setPreferredWidth(150);
            jTable1.getColumnModel().getColumn(3).setResizable(false);
            jTable1.getColumnModel().getColumn(3).setPreferredWidth(0);
        }

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jbtAtributosGrade, javax.swing.GroupLayout.PREFERRED_SIZE, 188, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(371, Short.MAX_VALUE))
            .addComponent(jPanel4, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
            .addComponent(jScrollPane1, javax.swing.GroupLayout.Alignment.TRAILING)
            .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(5, 5, 5)
                .addComponent(jbtAtributosGrade)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 198, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(jPanel4, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void jbtExcluirActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jbtExcluirActionPerformed
        if (javax.swing.JOptionPane.showConfirmDialog(null, "Deseja realmente excluir"
                + " este item?", "ATENÇÂO ", javax.swing.JOptionPane.YES_NO_OPTION) == 0) {

            ProdutoGradeDAO gradeDAO = new ProdutoGradeDAO();
            Long idProdutoGradeItens = 0L;
            DefaultTableModel amodelProdutoGradeItens; 
            idProdutoGradeItens = (Long) jTable1.getValueAt(jTable1.getSelectedRow(), 3);
            try{
                gradeDAO.excluirItemGrade(idProdutoGradeItens);
                ((DefaultTableModel) jTable1.getModel()).removeRow(jTable1.getSelectedRow());
                atualizarProdutoViewGradeItens();
                jbtExcluir.setEnabled(false);
                JOptionPane.showMessageDialog(null, "Item excluído da grade com sucesso !!!");                
            }catch (Exception e){
                    JOptionPane.showMessageDialog(null, "Este item não pode ser Excluído. Problemas com chaves Estrangeiras. "+e.getMessage());
            }
                        
        }
    }//GEN-LAST:event_jbtExcluirActionPerformed

    private void atualizarProdutoViewGradeItens() {
        DefaultTableModel amodelProdutoGradeItens;
        amodelProdutoGradeItens = (DefaultTableModel) ProdutoView.jTableGradeItens.getModel();
        amodelProdutoGradeItens.setNumRows(0);
        for (int i = 0; i < jTable1.getRowCount(); i++){
            amodelProdutoGradeItens.addRow(new Object[]{jTable1.getValueAt(i, 0),
                jTable1.getValueAt(i, 1), jTable1.getValueAt(i, 2) });
        }
    }
     private void atualizarProdutoViewGrade() {
        DefaultTableModel amodelProdutoGrade;
        amodelProdutoGrade = (DefaultTableModel) ProdutoView.jTableGrade.getModel();
        
        amodelProdutoGrade.addRow(new Object[]{ jtfGrade.getText()});
        
    }

    private void jbtExcluirKeyPressed(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_jbtExcluirKeyPressed
        if (evt.getKeyCode() == evt.VK_ENTER){
            String op = System.getProperty("os.name");
            if (!"Linux".equals(op))
            jbtExcluirActionPerformed(null);
        }
    }//GEN-LAST:event_jbtExcluirKeyPressed

    private void jbtCancelarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jbtCancelarActionPerformed

    }//GEN-LAST:event_jbtCancelarActionPerformed

    private void jbtCancelarKeyPressed(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_jbtCancelarKeyPressed
        if (evt.getKeyCode() == evt.VK_ENTER){
            String op = System.getProperty("os.name");
            if (!"Linux".equals(op)){
                System.out.println("programar...aqui.");
            }

        }
    }//GEN-LAST:event_jbtCancelarKeyPressed

    private void jbtSairActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jbtSairActionPerformed
        // TODO add your handling code here:
        dispose();
        menuView.Menu.produtoView = null;
        //  menuView.Menu.jmenuProduto.setEnabled(true);
    }//GEN-LAST:event_jbtSairActionPerformed

    private void jbtSairKeyPressed(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_jbtSairKeyPressed
        if (evt.getKeyCode() == evt.VK_ENTER){
            String op = System.getProperty("os.name");
            if (!"Linux".equals(op))
            dispose();

            
        }
    }//GEN-LAST:event_jbtSairKeyPressed

    private void jbtSalvarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jbtSalvarActionPerformed
         
        ProdutoGradeDAO daoGrade = new ProdutoGradeDAO();
        try{
            if (this.tipoBotao.equals("adicionar")) {
                adicionarProdutoGrade();
                daoGrade.salvar(produtoGrade);
                 JOptionPane.showMessageDialog(null, "Grade salva com sucesso.");
                 jbtAtributosGrade.setEnabled(false);
               
                 jtfGrade.requestFocus();
                 limpar();
            } else {
                if (this.tipoBotao.equals("alterar")){
                    adicionarProdutoGrade();
                    daoGrade.alterar(this.produtoGrade);
                    JOptionPane.showMessageDialog(null, "Grade alterada com sucesso.");
                }
            }        
         }catch (Exception e){
             JOptionPane.showMessageDialog(null, "Problemas ao salvar grade do produto.Error: "+e.getMessage());
         }                
    }//GEN-LAST:event_jbtSalvarActionPerformed

    private void adicionarProdutoGrade(){
        String atributo;
         float estoque = 0;
         float estoqueMin = 0;        
         listaItensGrade = new ArrayList<>();
         
         if (jtfGrade.getText().equals("") || jtfGrade.getText().isEmpty()){
            JOptionPane.showMessageDialog(null, "O campo: (grade) não pode, ser nullo ou vazio.");
            jtfGrade.requestFocus();
            return;
         }
         
         for (int i = 0; i < jTable1.getRowCount(); i ++){
            atributo = (jTable1.getValueAt(i, 0).toString().toUpperCase());
            estoqueMin = ((float) jTable1.getValueAt(i, 1));
            estoque = ((float) jTable1.getValueAt(i, 2));
            Long id = (Long) jTable1.getValueAt(i, 3);
             
            listaItensGrade.add(new ProdutoGradeItens(atributo, estoque, estoqueMin, id));
         }         
         
         
        // this.produtoGrade = new ProdutoGrade();
         this.produtoGrade.setGrade(jtfGrade.getText().toUpperCase());
         this.produtoGrade.setProduto(this.produto);
         this.produtoGrade.setListaGradeItens(listaItensGrade);
    }
    
    
    private void jbtSalvarKeyPressed(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_jbtSalvarKeyPressed
        if (evt.getKeyCode() == evt.VK_ENTER){

            String op = System.getProperty("os.name");
            if (!"Linux".equals(op))
            jbtSalvarActionPerformed(null);

            // salvar();

        }
    }//GEN-LAST:event_jbtSalvarKeyPressed

    private void jtfGradeKeyPressed(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_jtfGradeKeyPressed
         if (evt.getKeyCode() == evt.VK_ENTER){

//            if (!"Linux".equals(op))
//            jbtSalvarActionPerformed(null);
              if (jtfGrade.getText().equals("")){
                  JOptionPane.showMessageDialog(null, "Digite um cor válida.");
                  return;
              }  
              jbtAtributosGrade.setEnabled(true);
              jbtAtributosGrade.requestFocus();
            // salvar();

        }
    }//GEN-LAST:event_jtfGradeKeyPressed

    private void jbtAtributosGradeActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jbtAtributosGradeActionPerformed
        
       try{ 
             
              produtoGradeItenView = new ProdutoGradeItenView(new java.awt.Frame(), true);
              produtoGradeItenView.setLocationRelativeTo(null);
              produtoGradeItenView.setTitle("Itens da grade do produto");
              produtoGradeItenView.setVisible(true); 
           }catch(Exception e){
               JOptionPane.showMessageDialog(null, "Ocorreu um problema, ao abrir cadastro de grade.");
              
           } 
        
        
    }//GEN-LAST:event_jbtAtributosGradeActionPerformed

    private void jTable1MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jTable1MouseClicked
                
        jbtExcluir.setEnabled(true);
        
    }//GEN-LAST:event_jTable1MouseClicked

    /**
     * @param args the command line arguments
     */
//    public static void main(String args[]) {
//        /* Set the Nimbus look and feel */
//        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
//        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
//         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
//         */
//        try {
//            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
//                if ("Nimbus".equals(info.getName())) {
//                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
//                    break;
//                }
//            }
//        } catch (ClassNotFoundException ex) {
//            java.util.logging.Logger.getLogger(ProdutoGradeTesteView.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
//        } catch (InstantiationException ex) {
//            java.util.logging.Logger.getLogger(ProdutoGradeTesteView.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
//        } catch (IllegalAccessException ex) {
//            java.util.logging.Logger.getLogger(ProdutoGradeTesteView.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
//        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
//            java.util.logging.Logger.getLogger(ProdutoGradeTesteView.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
//        }
//        //</editor-fold>
//
//        /* Create and display the dialog */
//        java.awt.EventQueue.invokeLater(new Runnable() {
//            public void run() {
//                ProdutoGradeTesteView dialog = new ProdutoGradeTesteView(new javax.swing.JFrame(), true);
//                dialog.addWindowListener(new java.awt.event.WindowAdapter() {
//                    @Override
//                    public void windowClosing(java.awt.event.WindowEvent e) {
//                        System.exit(0);
//                    }
//                });
//                dialog.setVisible(true);
//            }
//        });
//    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JPanel jPanel4;
    private javax.swing.JScrollPane jScrollPane1;
    public static javax.swing.JTable jTable1;
    private javax.swing.JButton jbtAtributosGrade;
    private javax.swing.JButton jbtCancelar;
    private javax.swing.JButton jbtExcluir;
    private javax.swing.JButton jbtSair;
    private javax.swing.JButton jbtSalvar;
    private javax.swing.JLabel jlProduto;
    private javax.swing.JTextField jtfGrade;
    // End of variables declaration//GEN-END:variables
}
