/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package relatoriosView.venda;

import dao.PedidoDAO;
import java.math.BigDecimal;
import java.math.BigInteger;
import java.text.DateFormat;
import java.text.DecimalFormat;
import java.text.ParseException;
import java.text.SimpleDateFormat;
import java.util.ArrayList;
import java.util.Calendar;
import java.util.Date;
import java.util.GregorianCalendar;
import java.util.List;

import javax.swing.JOptionPane;
import javax.swing.table.DefaultTableModel;

import model.Pedido;
import model.PedidoItens;
import util.JTableFonteColunaDireitaAzul;
import util.JTableFonteColunaDireitaBlack;
import util.JTableFonteColunaDireitaVermelha;


/**
 *
 * @author daniel
 */
public class RelatorioVendaView extends javax.swing.JInternalFrame {

    /**
     * Creates new form RelatorioVenda
     */
    //SimpleDateFormat sdfDH = new SimpleDateFormat("dd/MM/yyyy' - 'HH':'mm");
    DateFormat df = new SimpleDateFormat ("dd/MM/yyyy");
    DateFormat dfHr = new SimpleDateFormat ("dd/MM/yyyy' - 'HH':'mm");
    public static List<Pedido> listaPedido = new ArrayList<>();
    PedidoDAO pedidoDAO = new PedidoDAO();
  //  String dataIniStr = null, dataFinStr = null;
    public static Date dataIni = null, dataFim = null;
    
    BigDecimal subtotal = new BigDecimal(BigInteger.ZERO);
    BigDecimal total = new BigDecimal(BigInteger.ZERO);
    BigDecimal custo = new BigDecimal(BigInteger.ZERO);
    BigDecimal custoTotal = new BigDecimal(BigInteger.ZERO);
    BigDecimal lucroLiqTotal = new BigDecimal(BigInteger.ZERO);
    BigDecimal lucroLiq = new BigDecimal(BigInteger.ZERO);
    String custoStr = null;
    String lucroLiqStr = null;
    String dataStr = null;
    
    
    
    
    public RelatorioVendaView() {
        initComponents();
        jlCustoTotal.setVisible(false);
        jlLucroLiq.setVisible(false);
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        buttonGroup1 = new javax.swing.ButtonGroup();
        jPanel1 = new javax.swing.JPanel();
        jPanel4 = new javax.swing.JPanel();
        jrbAVista = new javax.swing.JRadioButton();
        jrbVendaPrazo = new javax.swing.JRadioButton();
        jrbTodos = new javax.swing.JRadioButton();
        jPanel5 = new javax.swing.JPanel();
        jLabel1 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        jcbDtInicial = new util.JCalendar(true);
        jcbDtFinal = new util.JCalendar(true);
        jbtPesquisar = new javax.swing.JButton();
        jPanel2 = new javax.swing.JPanel();
        jScrollPane1 = new javax.swing.JScrollPane();
        jTable1 = new javax.swing.JTable();
        jPanel3 = new javax.swing.JPanel();
        jbtSair = new javax.swing.JButton();
        jbtImprimir = new javax.swing.JButton();
        jPanel6 = new javax.swing.JPanel();
        jLabel4 = new javax.swing.JLabel();
        jlCustoTotal = new javax.swing.JLabel();
        jLabel5 = new javax.swing.JLabel();
        jlLucroLiq = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        jtfTotal = new javax.swing.JTextField();

        setDefaultCloseOperation(javax.swing.WindowConstants.DISPOSE_ON_CLOSE);
        setTitle("Relatório Venda Por Período");

        jPanel1.setBorder(javax.swing.BorderFactory.createEtchedBorder());

        jPanel4.setBorder(javax.swing.BorderFactory.createTitledBorder("TIPO DE VENDA"));

        buttonGroup1.add(jrbAVista);
        jrbAVista.setText("Venda à Vista");
        jrbAVista.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jrbAVistaMouseClicked(evt);
            }
        });
        jrbAVista.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jrbAVistaActionPerformed(evt);
            }
        });
        jrbAVista.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyPressed(java.awt.event.KeyEvent evt) {
                jrbAVistaKeyPressed(evt);
            }
        });

        buttonGroup1.add(jrbVendaPrazo);
        jrbVendaPrazo.setText("Venda a Prazo");
        jrbVendaPrazo.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jrbVendaPrazoActionPerformed(evt);
            }
        });

        buttonGroup1.add(jrbTodos);
        jrbTodos.setText("Todos");
        jrbTodos.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jrbTodosActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout jPanel4Layout = new javax.swing.GroupLayout(jPanel4);
        jPanel4.setLayout(jPanel4Layout);
        jPanel4Layout.setHorizontalGroup(
            jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel4Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jrbAVista, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addGroup(jPanel4Layout.createSequentialGroup()
                        .addComponent(jrbVendaPrazo)
                        .addGap(0, 65, Short.MAX_VALUE)))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jrbTodos)
                .addContainerGap())
        );
        jPanel4Layout.setVerticalGroup(
            jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel4Layout.createSequentialGroup()
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addGroup(jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jrbAVista)
                    .addComponent(jrbTodos))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jrbVendaPrazo)
                .addGap(30, 30, 30))
        );

        jPanel5.setBorder(javax.swing.BorderFactory.createTitledBorder("PERÍODO"));

        jLabel1.setText("Data Inicial");

        jLabel2.setText("Data Final");

        jcbDtInicial.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jcbDtInicialMouseClicked(evt);
            }
        });
        jcbDtInicial.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyTyped(java.awt.event.KeyEvent evt) {
                jcbDtInicialKeyTyped(evt);
            }
            public void keyPressed(java.awt.event.KeyEvent evt) {
                jcbDtInicialKeyPressed(evt);
            }
        });

        javax.swing.GroupLayout jPanel5Layout = new javax.swing.GroupLayout(jPanel5);
        jPanel5.setLayout(jPanel5Layout);
        jPanel5Layout.setHorizontalGroup(
            jPanel5Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel5Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel5Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jcbDtInicial, javax.swing.GroupLayout.PREFERRED_SIZE, 117, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel1))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 63, Short.MAX_VALUE)
                .addGroup(jPanel5Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jcbDtFinal, javax.swing.GroupLayout.PREFERRED_SIZE, 114, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel2))
                .addContainerGap())
        );
        jPanel5Layout.setVerticalGroup(
            jPanel5Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel5Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel5Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel2)
                    .addComponent(jLabel1))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(jPanel5Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jcbDtFinal, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jcbDtInicial, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        jbtPesquisar.setIcon(new javax.swing.ImageIcon(getClass().getResource("/imagens/Find.png"))); // NOI18N
        jbtPesquisar.setText("Pesquisar");
        jbtPesquisar.setEnabled(false);
        jbtPesquisar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jbtPesquisarActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jPanel4, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jPanel5, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addComponent(jbtPesquisar, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addContainerGap())
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel1Layout.createSequentialGroup()
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                            .addComponent(jPanel5, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addComponent(jPanel4, javax.swing.GroupLayout.PREFERRED_SIZE, 0, Short.MAX_VALUE))
                        .addContainerGap())
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel1Layout.createSequentialGroup()
                        .addComponent(jbtPesquisar, javax.swing.GroupLayout.PREFERRED_SIZE, 75, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(20, 20, 20))))
        );

        jTable1.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {

            },
            new String [] {
                "Nº PEDIDO", "DATA / HORA", "CLIENTE", "R$ TOTAL", "R$ CUSTO", "R$ LUCRO B."
            }
        ) {
            Class[] types = new Class [] {
                java.lang.String.class, java.lang.String.class, java.lang.String.class, java.lang.String.class, java.lang.String.class, java.lang.Object.class
            };
            boolean[] canEdit = new boolean [] {
                false, false, false, false, false, false
            };

            public Class getColumnClass(int columnIndex) {
                return types [columnIndex];
            }

            public boolean isCellEditable(int rowIndex, int columnIndex) {
                return canEdit [columnIndex];
            }
        });
        jTable1.setAutoResizeMode(javax.swing.JTable.AUTO_RESIZE_OFF);
        jScrollPane1.setViewportView(jTable1);
        if (jTable1.getColumnModel().getColumnCount() > 0) {
            jTable1.getColumnModel().getColumn(0).setPreferredWidth(110);
            jTable1.getColumnModel().getColumn(1).setPreferredWidth(115);
            jTable1.getColumnModel().getColumn(2).setPreferredWidth(245);
            jTable1.getColumnModel().getColumn(3).setPreferredWidth(110);
            jTable1.getColumnModel().getColumn(4).setPreferredWidth(110);
            jTable1.getColumnModel().getColumn(5).setPreferredWidth(110);
        }

        javax.swing.GroupLayout jPanel2Layout = new javax.swing.GroupLayout(jPanel2);
        jPanel2.setLayout(jPanel2Layout);
        jPanel2Layout.setHorizontalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jScrollPane1, javax.swing.GroupLayout.DEFAULT_SIZE, 802, Short.MAX_VALUE)
        );
        jPanel2Layout.setVerticalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jScrollPane1, javax.swing.GroupLayout.DEFAULT_SIZE, 327, Short.MAX_VALUE)
        );

        jPanel3.setBorder(javax.swing.BorderFactory.createEtchedBorder());

        jbtSair.setIcon(new javax.swing.ImageIcon(getClass().getResource("/imagens/exit_1.png"))); // NOI18N
        jbtSair.setText("Sair");
        jbtSair.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jbtSairActionPerformed(evt);
            }
        });

        jbtImprimir.setIcon(new javax.swing.ImageIcon(getClass().getResource("/imagens/print-icon.png"))); // NOI18N
        jbtImprimir.setText("Imprimir");
        jbtImprimir.setEnabled(false);
        jbtImprimir.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jbtImprimirActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout jPanel3Layout = new javax.swing.GroupLayout(jPanel3);
        jPanel3.setLayout(jPanel3Layout);
        jPanel3Layout.setHorizontalGroup(
            jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel3Layout.createSequentialGroup()
                .addComponent(jbtImprimir, javax.swing.GroupLayout.PREFERRED_SIZE, 128, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(jbtSair, javax.swing.GroupLayout.PREFERRED_SIZE, 90, javax.swing.GroupLayout.PREFERRED_SIZE))
        );
        jPanel3Layout.setVerticalGroup(
            jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                .addComponent(jbtSair, javax.swing.GroupLayout.PREFERRED_SIZE, 41, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addComponent(jbtImprimir, javax.swing.GroupLayout.PREFERRED_SIZE, 41, javax.swing.GroupLayout.PREFERRED_SIZE))
        );

        jPanel6.setBorder(javax.swing.BorderFactory.createEtchedBorder());

        jLabel4.setText("CUSTO TOTAL    R$:");

        jlCustoTotal.setForeground(java.awt.Color.red);
        jlCustoTotal.setHorizontalAlignment(javax.swing.SwingConstants.RIGHT);
        jlCustoTotal.setText("jLabel5");
        jlCustoTotal.setInheritsPopupMenu(false);

        jLabel5.setText("LUCRO BRUTO   R$:");

        jlLucroLiq.setHorizontalAlignment(javax.swing.SwingConstants.RIGHT);
        jlLucroLiq.setText("jLabel6");

        jLabel3.setText("RECEITA TOTAL   R$:");

        jtfTotal.setBackground(new java.awt.Color(255, 244, 131));
        jtfTotal.setFont(new java.awt.Font("SansSerif", 1, 18)); // NOI18N
        jtfTotal.setForeground(java.awt.Color.blue);
        jtfTotal.setHorizontalAlignment(javax.swing.JTextField.RIGHT);

        javax.swing.GroupLayout jPanel6Layout = new javax.swing.GroupLayout(jPanel6);
        jPanel6.setLayout(jPanel6Layout);
        jPanel6Layout.setHorizontalGroup(
            jPanel6Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel6Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel6Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel6Layout.createSequentialGroup()
                        .addComponent(jLabel4)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addComponent(jlCustoTotal, javax.swing.GroupLayout.PREFERRED_SIZE, 83, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addComponent(jLabel3)
                        .addGap(46, 46, 46)
                        .addComponent(jtfTotal, javax.swing.GroupLayout.PREFERRED_SIZE, 198, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(jPanel6Layout.createSequentialGroup()
                        .addComponent(jLabel5)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addComponent(jlLucroLiq, javax.swing.GroupLayout.PREFERRED_SIZE, 85, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(0, 0, Short.MAX_VALUE)))
                .addContainerGap())
        );
        jPanel6Layout.setVerticalGroup(
            jPanel6Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel6Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel6Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jLabel3)
                    .addGroup(jPanel6Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                        .addComponent(jLabel4)
                        .addComponent(jlCustoTotal)
                        .addComponent(jtfTotal, javax.swing.GroupLayout.PREFERRED_SIZE, 39, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(jPanel6Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel5)
                    .addComponent(jlLucroLiq, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                .addContainerGap())
        );

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
            .addComponent(jPanel2, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
            .addComponent(jPanel3, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
            .addComponent(jPanel6, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jPanel2, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jPanel6, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jPanel3, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void jrbAVistaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jrbAVistaActionPerformed
       jbtPesquisar.setEnabled(true);
       
    }//GEN-LAST:event_jrbAVistaActionPerformed

    private void jbtSairActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jbtSairActionPerformed
        dispose();
    }//GEN-LAST:event_jbtSairActionPerformed

    private void jrbAVistaKeyPressed(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_jrbAVistaKeyPressed
        if (evt.getKeyCode() == evt.VK_ENTER){
           if (jrbAVista.isSelected()){
               jcbDtInicial.requestFocus();
           }
           //else
//              jrbVendaPrazo.requestFocus();
        }
    }//GEN-LAST:event_jrbAVistaKeyPressed

    private void jrbAVistaMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jrbAVistaMouseClicked

        // TODO add your handling code here:
    }//GEN-LAST:event_jrbAVistaMouseClicked

    private void jcbDtInicialKeyPressed(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_jcbDtInicialKeyPressed
      
    }//GEN-LAST:event_jcbDtInicialKeyPressed

    private void jcbDtInicialMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jcbDtInicialMouseClicked
        jcbDtFinal.requestFocus();
    }//GEN-LAST:event_jcbDtInicialMouseClicked

    private void jcbDtInicialKeyTyped(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_jcbDtInicialKeyTyped
         if (evt.getKeyCode() == 13) {
            System.out.println("Keypress");
            
        }
    }//GEN-LAST:event_jcbDtInicialKeyTyped

    private void jbtPesquisarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jbtPesquisarActionPerformed

        
        DefaultTableModel amodel = (DefaultTableModel) jTable1.getModel();
        amodel.setNumRows(0);
      
        
        
        GregorianCalendar gc = new GregorianCalendar();      
        Calendar c = new GregorianCalendar();
        total = new BigDecimal(BigInteger.ZERO);
        subtotal = new BigDecimal(BigInteger.ZERO);
        custo = new BigDecimal(BigInteger.ZERO);
        custoStr = null;
        custoTotal = new BigDecimal(BigInteger.ZERO);
        //Validação de Data Inicial e Final.
       
        if (!jcbDtInicial.getSelectedItem().equals("")){            
            gc = (GregorianCalendar) jcbDtInicial.getSelectedItem();
            
            
            dataIni = gc.getTime();
            String dataStr = df.format(dataIni);
            try {
                dataIni = df.parse(dataStr);
            } catch (ParseException ex) {
                JOptionPane.showMessageDialog(null, "Data inicial inválida.");
            }
        }else{
             JOptionPane.showMessageDialog(null, "A data inicial está vazia");
             return;
        }
        if (!jcbDtFinal.getSelectedItem().equals("")){           
            gc = (GregorianCalendar) jcbDtFinal.getSelectedItem();
            dataFim = gc.getTime();
        }else{
             JOptionPane.showMessageDialog(null, "A data final está vazia");
             return;
        }    
        if (dataIni.getTime() > dataFim.getTime()){
            JOptionPane.showMessageDialog(null, "Data Inicial maior que a Data Final");
            return;
        }
        
        if (jrbAVista.isSelected()){
            try{
                                
                listaPedido = pedidoDAO.listaPedidoAVistaPorPeriodo(dataIni, dataFim);

                if (listaPedido.isEmpty()){
                    JOptionPane.showMessageDialog(null, "Não têm Venda a Prazo neste Período");
                    return;
                }            
                PedidoRel pRel = new PedidoRel();
           
                BigDecimal totalPedido = new BigDecimal(BigInteger.ZERO);
                for (Pedido pedido : listaPedido){                    
                    
                    pRel.setIdVenda(String.valueOf(pedido.getId()));
                    pRel.setCliente(pedido.getCliente().getNome());                    
                    dataStr = dfHr.format(pedido.getDtCad());
                    pRel.setDtVenda(dataStr);
                    
                    
                    for (PedidoItens itens : pedido.getListaItens()){
                        subtotal = subtotal.add(itens.getVlSubtotal());
                        custoStr = String.valueOf(itens.getProduto().getVl_compra());
                        custo = BigDecimal.valueOf(itens.getProduto().getVl_compra());                         
                        custo = custo.multiply((itens.getQuantidade()));
                        custoTotal = custoTotal.add(custo);  
                        lucroLiq = (subtotal.subtract(custo));                        
                    }
                    pRel.setTotal(String.valueOf(subtotal));   
                    if (pRel.getCliente().equals("ADMIN"))
                        pRel.setCliente("CONSUMIDOR");
                    
                    lucroLiqStr = (new DecimalFormat("#,##0.00").format(lucroLiq));
                    custoStr = (new DecimalFormat("#,##0.00").format(custo));
                    // TODO code application logic here 
//                    if (!pedido.getListaPagamento().isEmpty())
//                      totalPedido = pedido.getListaPagamento().get(0).getTotal();
//                    else
//                        totalPedido = new BigDecimal(BigInteger.ZERO);
                    //Arrumar
                    amodel.addRow(new Object[]{pRel.getIdVenda(), dataStr, pRel.getCliente(), subtotal, custoStr, lucroLiqStr});
                    
                    
                    //Coloca coluna da jtable para a direita e muda cor da fonte.
                    jTable1.getColumnModel().getColumn(3).setCellRenderer(new JTableFonteColunaDireitaAzul());
                    jTable1.getColumnModel().getColumn(4).setCellRenderer(new JTableFonteColunaDireitaVermelha());
                    jTable1.getColumnModel().getColumn(5).setCellRenderer(new JTableFonteColunaDireitaBlack());
                    
                    
                    total = total.add(subtotal);
                    subtotal = BigDecimal.ZERO;
                    lucroLiqTotal = (total.subtract(custoTotal));
                     
                    jlCustoTotal.setText(new DecimalFormat("#,##0.00").format(custoTotal));
                    jlLucroLiq.setText(new DecimalFormat("#,##0.00").format(lucroLiqTotal));
                }   
                jtfTotal.setText(String.valueOf(new DecimalFormat("#,##0.00").format(total)));
                jbtImprimir.setEnabled(true);
                jlCustoTotal.setVisible(true);
                jlLucroLiq.setVisible(true);
            }catch (Exception ex){
                JOptionPane.showMessageDialog(null, "Problemas ao Carregar Tabela de Venda à Vista"+ex.getMessage());
                ex.printStackTrace();
            }
        }else
            if (jrbVendaPrazo.isSelected()){
              //  total = new BigDecimal(BigInteger.ZERO);
                 try{
                                
                listaPedido = pedidoDAO.listaPedidoAPrazoPorPeriodo(dataIni, dataFim);
          System.out.println("vou fazer a pesquisa passei da pesquisa");
                if (listaPedido.isEmpty()){
                    JOptionPane.showMessageDialog(null, "Não têm Venda a Prazo neste Período");
                    return;
                }            
                PedidoRel pRel = new PedidoRel();
           
                BigDecimal totalPedido = new BigDecimal(BigInteger.ZERO);
                for (Pedido pedido : listaPedido){                    
                    
                    pRel.setIdVenda(String.valueOf(pedido.getId()));
                    pRel.setCliente(pedido.getCliente().getNome());                    
                    dataStr = dfHr.format(pedido.getDtCad());
                    pRel.setDtVenda(dataStr);
                    
                    
                    for (PedidoItens itens : pedido.getListaItens()){
                        subtotal = subtotal.add(itens.getVlSubtotal());
                        custoStr = String.valueOf(itens.getProduto().getVl_compra());
                        custo = BigDecimal.valueOf(itens.getProduto().getVl_compra());                         
                        custo = custo.multiply((itens.getQuantidade()));
                        custoTotal = custoTotal.add(custo);  
                        lucroLiq = (subtotal.subtract(custo));
                        
                        System.out.println("totalPedido ="+totalPedido);
                         System.out.println("subtotal ="+subtotal);
                    }
                    pRel.setTotal(String.valueOf(subtotal));   
                    if (pRel.getCliente().equals("ADMIN"))
                        pRel.setCliente("CONSUMIDOR");
                    
                    lucroLiqStr = (new DecimalFormat("#,##0.00").format(lucroLiq));
                    custoStr = (new DecimalFormat("#,##0.00").format(custo));
                    
                     // totalPedido = pedido.getListaPagamento().get(0).getTotal();
                    //Arrumar
                    amodel.addRow(new Object[]{pRel.getIdVenda(), dataStr, pRel.getCliente(), subtotal, custoStr, lucroLiqStr});
                    
                    
                    //Coloca coluna da jtable para a direita e muda cor da fonte.
                    jTable1.getColumnModel().getColumn(3).setCellRenderer(new JTableFonteColunaDireitaAzul());
                    jTable1.getColumnModel().getColumn(4).setCellRenderer(new JTableFonteColunaDireitaVermelha());
                    jTable1.getColumnModel().getColumn(5).setCellRenderer(new JTableFonteColunaDireitaBlack());
                    
                    
                    total = total.add(subtotal);
                    subtotal = BigDecimal.ZERO;
                    lucroLiqTotal = (total.subtract(custoTotal));
                     
                    jlCustoTotal.setText(new DecimalFormat("#,##0.00").format(custoTotal));
                    jlLucroLiq.setText(new DecimalFormat("#,##0.00").format(lucroLiqTotal));
                }   
                jtfTotal.setText(String.valueOf(new DecimalFormat("#,##0.00").format(total)));
                jbtImprimir.setEnabled(true);
                jlCustoTotal.setVisible(true);
                jlLucroLiq.setVisible(true);
            }catch (Exception ex){
                JOptionPane.showMessageDialog(null, "Problemas ao Carregar Tabela de Venda a Prazo"+ex.getMessage());
                ex.printStackTrace();
            }
                
                
                
            }else
                if (jrbTodos.isSelected()){
                    try {

                        listaPedido = pedidoDAO.listaPedidoTodosPorPeriodo(dataIni, dataFim);
                        
                        if (listaPedido.isEmpty()) {
                            JOptionPane.showMessageDialog(null, "Não têm Venda a Prazo neste Período");
                            return;
                        }
                        PedidoRel pRel = new PedidoRel();

                        BigDecimal totalPedido = new BigDecimal(BigInteger.ZERO);
                        for (Pedido pedido : listaPedido) {

                            pRel.setIdVenda(String.valueOf(pedido.getId()));
                            pRel.setCliente(pedido.getCliente().getNome());
                            dataStr = dfHr.format(pedido.getDtCad());
                            pRel.setDtVenda(dataStr);

                            for (PedidoItens itens : pedido.getListaItens()) {
                                subtotal = subtotal.add(itens.getVlSubtotal());
                                custoStr = String.valueOf(itens.getProduto().getVl_compra());
                                custo = BigDecimal.valueOf(itens.getProduto().getVl_compra());
                                custo = custo.multiply((itens.getQuantidade()));
                                custoTotal = custoTotal.add(custo);
                                lucroLiq = (subtotal.subtract(custo));

                            }
                            pRel.setTotal(String.valueOf(subtotal));
                            if (pRel.getCliente().equals("ADMIN")) {
                                pRel.setCliente("CONSUMIDOR");
                            }

                            lucroLiqStr = (new DecimalFormat("#,##0.00").format(lucroLiq));
                            custoStr = (new DecimalFormat("#,##0.00").format(custo));

                            // totalPedido = pedido.getListaPagamento().get(0).getTotal();
                            //Arrumar
                            amodel.addRow(new Object[]{pRel.getIdVenda(), dataStr, pRel.getCliente(), subtotal, custoStr, lucroLiqStr});

                            //Coloca coluna da jtable para a direita e muda cor da fonte.
                            jTable1.getColumnModel().getColumn(3).setCellRenderer(new JTableFonteColunaDireitaAzul());
                            jTable1.getColumnModel().getColumn(4).setCellRenderer(new JTableFonteColunaDireitaVermelha());
                            jTable1.getColumnModel().getColumn(5).setCellRenderer(new JTableFonteColunaDireitaBlack());

                            total = total.add(subtotal);
                            subtotal = BigDecimal.ZERO;
                            lucroLiqTotal = (total.subtract(custoTotal));

                            jlCustoTotal.setText(new DecimalFormat("#,##0.00").format(custoTotal));
                            jlLucroLiq.setText(new DecimalFormat("#,##0.00").format(lucroLiqTotal));
                        }
                        jtfTotal.setText(String.valueOf(new DecimalFormat("#,##0.00").format(total)));
                        jbtImprimir.setEnabled(true);
                        jlCustoTotal.setVisible(true);
                        jlLucroLiq.setVisible(true);
                    } catch (Exception ex) {
                        JOptionPane.showMessageDialog(null, "Problemas ao Carregar Tabela de Venda a Prazo" + ex.getMessage());
                        ex.printStackTrace();
                    }
            }

    }//GEN-LAST:event_jbtPesquisarActionPerformed

    private void jbtImprimirActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jbtImprimirActionPerformed

        
//        ImprimeRelatorio imprimir = new ImprimeRelatorio();
//        List<PedidoRel> listaVenda = new ArrayList<>();
//        PedidoRel pedidoRel = new PedidoRel();
//       // float totalEntrada = 0, totalSaida = 0, totalSaldoFinal = 0;
//        String tipo = null, dtIni = null, dtFim = null, total = null;
//        dtIni = df.format(dataIni);
//        dtFim = df.format(dataFim);
//        for (int i = 0; i < jTable1.getRowCount(); i ++){
//            
//            pedidoRel.setIdVenda((jTable1.getValueAt(i, 0).toString()));
//            pedidoRel.setDtVenda(jTable1.getValueAt(i, 1).toString());
//            pedidoRel.setCliente(jTable1.getValueAt(i, 2).toString());
//            pedidoRel.setTotal((jTable1.getValueAt(i, 3).toString()));
//        
//            listaVenda.add(new PedidoRel(pedidoRel.getIdVenda(), pedidoRel.getCliente(),
//            pedidoRel.getTotal(), pedidoRel.getDtVenda()));
//        }
//        if (jrbAVista.isSelected())
//            tipo = "À VISTA";
//        else
//            if (jrbVendaPrazo.isSelected())
//                tipo = "A PRAZO";
//            else
//                if (jrbTodos.isSelected())
//                    tipo = "TODOS";
//      
//        
//        total = jtfTotal.getText();
//      
//        try {
//            imprimir.relatorioVendaPorPeriodo(listaVenda, tipo, dtIni, dtFim, total);
//        } catch (JRException ex) {
//            //Logger.getLogger(RelatorioVendaView.class.getName()).log(Level.SEVERE, null, ex);
//            JOptionPane.showMessageDialog(null, "Error ao gerar o Relatório. Error: "+ex.getMessage());
//        }
        
      if (jrbAVista.isSelected() || jrbVendaPrazo.isSelected()){  
        TipodeImpressaoView p = new TipodeImpressaoView(new java.awt.Frame(), false);
        p.setTitle("Escolha o Tipo de Relatório.");
        p.setLocationRelativeTo(null); // centraliza a tela
        p.setVisible(true);
      }



    }//GEN-LAST:event_jbtImprimirActionPerformed

    private void jrbVendaPrazoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jrbVendaPrazoActionPerformed
         jbtPesquisar.setEnabled(true);
    }//GEN-LAST:event_jrbVendaPrazoActionPerformed

    private void jrbTodosActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jrbTodosActionPerformed

         jbtPesquisar.setEnabled(true);
    }//GEN-LAST:event_jrbTodosActionPerformed

    /**
     * @param args the command line arguments
     */
//    public static void main(String args[]) {
//        /* Set the Nimbus look and feel */
//        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
//        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
//         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
//         */
//        try {
//            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
//                if ("Nimbus".equals(info.getName())) {
//                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
//                    break;
//                }
//            }
//        } catch (ClassNotFoundException ex) {
//            java.util.logging.Logger.getLogger(RelatorioVenda.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
//        } catch (InstantiationException ex) {
//            java.util.logging.Logger.getLogger(RelatorioVenda.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
//        } catch (IllegalAccessException ex) {
//            java.util.logging.Logger.getLogger(RelatorioVenda.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
//        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
//            java.util.logging.Logger.getLogger(RelatorioVenda.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
//        }
//        //</editor-fold>
//
//        /* Create and display the form */
//        java.awt.EventQueue.invokeLater(new Runnable() {
//            public void run() {
//                new RelatorioVenda().setVisible(true);
//            }
//        });
//    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.ButtonGroup buttonGroup1;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JPanel jPanel2;
    private javax.swing.JPanel jPanel3;
    private javax.swing.JPanel jPanel4;
    private javax.swing.JPanel jPanel5;
    private javax.swing.JPanel jPanel6;
    private javax.swing.JScrollPane jScrollPane1;
    public static javax.swing.JTable jTable1;
    private javax.swing.JButton jbtImprimir;
    private javax.swing.JButton jbtPesquisar;
    private javax.swing.JButton jbtSair;
    private javax.swing.JComboBox<String> jcbDtFinal;
    private javax.swing.JComboBox<String> jcbDtInicial;
    private javax.swing.JLabel jlCustoTotal;
    private javax.swing.JLabel jlLucroLiq;
    public static javax.swing.JRadioButton jrbAVista;
    public static javax.swing.JRadioButton jrbTodos;
    public static javax.swing.JRadioButton jrbVendaPrazo;
    public static javax.swing.JTextField jtfTotal;
    // End of variables declaration//GEN-END:variables
}
